name: macOS-10.13_$(date:yyyyMMdd)$(rev:.r)_unstable

trigger: none
pr:
  autoCancel: true
  branches:
    include:
    - main

jobs:
- template: image-generation.yml
  parameters:
    image_label: 'macOS High Sierra'
    base_image_name: 'clean-macOS-10.13.6-380Gb-SIPoff_runner'
    template_path: 'templates/macOS-10.13.json'
    target_datastore: 'ds-image'
