name: macOS-11_$(date:yyyyMMdd)$(rev:.r)_unstable
schedules:
- cron: '45 0 * * *'
  displayName: Daily
  branches:
    include:
    - main
  always: true

trigger: none
pr:
  autoCancel: true
  branches:
    include:
    - main

jobs:
- template: image-generation.yml
  parameters:
    image_label: 'macOS Big Sur'
    base_image_name: 'clean-macOS-11-380Gb-runner'
    template_path: 'templates/macOS-11.json'
    target_datastore: 'ds-image'
