name: macOS-12_$(date:yyyyMMdd)$(rev:.r)_unstable
schedules:
- cron: '45 1 * * 1'
  displayName: Weekly
  branches:
    include:
    - main
  always: true

trigger: none

variables:
- group: Mac-Cloud Image Generation

jobs:
- template: image-generation.yml
  parameters:
    image_label: 'macOS Monterey'
    base_image_name: 'clean-macOS-12-380Gb-runner'
    template_path: 'templates/macOS-12.pkr.hcl'
    target_datastore: 'ds-image'
    variable_group_name: 'Mac-Cloud Secondary Image Generation'
    primary_agent: 'false'
