github: tijuks
patreon: tijuks
ko_fi: tijuks
custom:\n  - https://buymeacoffee.com/tijuks\n  - https://www.paypal.me/tijuks\n  - https://github.com/sponsors/tijuks\n  - https://opencollective.com/tijuks\n
