commands_restrictions:
  update:
    conditions:
      - or:
          - sender-permission >= reader
          - sender = {{author}}
  rebase:
    conditions:
      - or:
          - sender-permission >= reader
          - sender = {{author}}
  squash:
    conditions:
      - or:
          - sender-permission >= reader
          - sender = {{author}}
