trigger:
  batch: true

variables:
 AZURE_SUBSCRIPTION_ID: $(AZURE_SUBSCRIPTION_ID)
 GITHUB_TOKEN: $(GITHUB_TOKEN)


stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    workspace:
      clean: all
    displayName: Build
    pool: vmss-windows

    steps:
    - powershell: |
        Import-Module .\helpers\GenerateResourcesAndImage.ps1
        GenerateResourcesAndImage -SubscriptionId $(AZURE_SUBSCRIPTION_ID) -ImageGenerationRepositoryRoot "$pwd" -ImageType windows2019 -AzureLocation "west US" -GithubFeedToken $(GITHUB_TOKEN) -ResourceGroupName "buildagents-$(Build.BuildId)"
      displayName: build resources
