trigger:
  batch: true


stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    workspace:
      clean: all
    displayName: Build
    pool: vmss-windows

    steps:
    - powershell: |
        Import-Module .\helpers\GenerateResourcesAndImage.ps1
        # GenerateResourcesAndImage -SubscriptionId ${env:AZURE_SUBSCRIPTION_ID} -ImageGenerationRepositoryRoot "$pwd" -ImageType windows2019 -AzureLocation "west US" -GithubFeedToken ${env:GITHUB_TOKEN} -ResourceGroupName "buildagents-$(Build.BuildId)"
      displayName: build resources
