trigger:
  batch: true

variables:
 AZURE_SUB_ID: $(AZURE_SUBSCRIPTION_ID)
 GH_TOKEN: $(GITHUB_TOKEN)


stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    workspace:
      clean: all
    displayName: Build
    pool: vmss-windows

    steps:
    - task: AzureCLI@2
      displayName: Azure CLI
      inputs:
        azureSubscription: azr-lsg-gss-global(0fc6d504-3fba-461e-934e-25744d5c7f6c)
        scriptType: ps
        scriptLocation: inlineScript
        inlineScript: |
          $RmContext = Get-Content C:\Users\AzDevOps\.Azure\AzureRmContext.json | ConvertFrom-Json
          Write-Host $RmContent
          Install-Module -Name Az -Scope CurrentUser -Repository PSGallery -Force -AllowClobber
          Uninstall-AzureRm
          Import-Module .\helpers\GenerateResourcesAndImage.ps1
          GenerateResourcesAndImage -AzureClientId $(AZURECLIENTID) -AzureClientSecret $(AzureClientSecret) -AzureTenantId $(AzureTenantId) -SubscriptionId ca9a7991-a1c8-4951-a321-11e7c1ffc279 -ImageGenerationRepositoryRoot "$pwd" -ImageType windows2019 -AzureLocation "west US" -ResourceGroupName gs3-build-agent-images
