trigger:
  batch: true

variables:
 AZURE_SUB_ID: $(AZURE_SUBSCRIPTION_ID)
 GH_TOKEN: $(GITHUB_TOKEN)


stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    workspace:
      clean: all
    displayName: Build
    pool: vmss-windows

    steps:
    - task: AzureCLI@2
      displayName: Azure CLI
      inputs:
        azureSubscription: dfc69404-c6a0-4262-970c-08dec22ffb31
        scriptType: ps
        scriptLocation: inlineScript
        inlineScript: |
          az --version
          az account show
          Get-Content C:\Users\AzDevOps\.Azure\AzureRmContext.json
          Install-Module -Name Az -Scope CurrentUser -Repository PSGallery -Force -AllowClobber
          Uninstall-AzureRm
          Import-Module .\helpers\GenerateResourcesAndImage.ps1
          GenerateResourcesAndImage -AzureClientId $(AZURECLIENTID) -AzureClientSecret $(AzureClientSecret) -AzureTenantId $(AzureTenantId) -SubscriptionId ca9a7991-a1c8-4951-a321-11e7c1ffc279 -ImageGenerationRepositoryRoot "$pwd" -ImageType windows2019 -AzureLocation "west US" -ResourceGroupName gs3-build-agent-images
