trigger:
  batch: true

variables:
 AZURE_SUB_ID: $(AZURE_SUBSCRIPTION_ID)
 GH_TOKEN: $(GITHUB_TOKEN)


stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    workspace:
      clean: all
    displayName: Build
    pool: vmss-windows

    steps:
    - task: AzureCLI@2
      displayName: Azure CLI
      inputs:
        azureSubscription: azr-lsg-gss-global(0fc6d504-3fba-461e-934e-25744d5c7f6c)
        scriptType: ps
        scriptLocation: inlineScript
        addSpnToEnvironment: true

        inlineScript: |
          # dir env:
          Write-Host "servicePrincipalId: ${servicePrincipalId} : ${env:servicePrincipalId}"
          Install-Module -Name Az -Scope CurrentUser -Repository PSGallery -Force -AllowClobber
          Uninstall-AzureRm
          Import-Module .\helpers\GenerateResourcesAndImage.ps1
          GenerateResourcesAndImage -AzureClientId ${env:servicePrincipalId} -AzureClientSecret ${env:servicePrincipalKey} -AzureTenantId $(az account show --query 'tenantId' --output tsv) -SubscriptionId $(az account show --query 'id' --output tsv) -ImageGenerationRepositoryRoot "$pwd" -ImageType windows2019 -AzureLocation "west US" -ResourceGroupName gss-build-agent-images
