trigger:
  batch: true

variables:
 AZURE_SUB_ID: $(AZURE_SUBSCRIPTION_ID)
 GH_TOKEN: $(GITHUB_TOKEN)


stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    workspace:
      clean: all
    displayName: Build
    pool: vmss-windows

    steps:
    - powershell: |
        Uninstall-AzureRm
        Install-Module -Name Az -Scope CurrentUser -Repository PSGallery -Force -AllowClobber
        Import-Module .\helpers\GenerateResourcesAndImage.ps1
        GenerateResourcesAndImage -SubscriptionId $(AZURE_SUB_ID) -ImageGenerationRepositoryRoot "$pwd" -ImageType windows2019 -AzureLocation "west US" -GithubFeedToken $(GH_TOKEN) -ResourceGroupName "buildagents-$(Build.BuildId)"
      displayName: build resources
