trigger:
  batch: true

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    workspace:
      clean: all
    displayName: Build
    pool: vmss-windows

    steps:
    - powershell: |
        Uninstall-AzureRm
        Install-Module -Name Az -Scope CurrentUser -Repository PSGallery -Force -AllowClobber
        Import-Module .\helpers\GenerateResourcesAndImage.ps1
        GenerateResourcesAndImage -SubscriptionId 0fc6d504-3fba-461e-934e-25744d5c7f6c -ImageGenerationRepositoryRoot "$pwd" -ImageType windows2019 -AzureLocation "west US" -ResourceGroupName "buildagents-$(Build.BuildId)"

      displayName: build resources
