pool: 'demo-desvops'

trigger: none

stages:
- stage: Terraform_plan
  displayName: 'Create terraform plan'
  variables:
  - template: variable_groups/terraform-sample-variables.yml
  - group: terraform-sample
  jobs:
    - job: CreatePlanAndApply
      timeoutInMinutes: 180
      steps:
      - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
        displayName: Install Terraform $(terraform-version)
        inputs:
          terraformVersion: $(terraform-version)
      - task: CmdLine@2
        displayName: Terraform Init
        inputs:
          script: terraform init -backend-config="access_key=$(access_key)" -backend-config="storage_account_name=$(storage_account_name)" -backend-config="container_name=$(container_name)" -backend-config="key=$(key)"
          workingDirectory: $(terafform-workdir)
      - task: CmdLine@2
        displayName: Terraform Validate
        inputs:
          script: terraform validate
          workingDirectory: $(terafform-workdir)
      - task: CmdLine@2
        displayName: Terraform Apply
        inputs:
          script: terraform apply -auto-approve -input=false -var="spn-client-id=$(spn_client_id)" -var="spn-client-secret=$(spn_client_secret)" -var="spn-tenant-id=$(spn_tenant_id)" -var="subscription-id=$(subscription_id)" 
          workingDirectory: $(terafform-workdir)
      - task: CmdLine@2
        inputs:
          script: terraform output -json > $(Build.ArtifactStagingDirectory)/terraform-output.json
          workingDirectory: $(terafform-workdir)
      - task: PublishBuildArtifacts@1
        inputs:
          pathToPublish: '$(Build.ArtifactStagingDirectory)'
          artifactName: drop                
  