schedules:
- cron: "0 0 * * *"
  displayName: Daily
  branches:
    include:
    - master
  always: true

trigger: none
pr:
  autoCancel: true
  branches:
    include:
    - master

jobs:
- template: image-generation.yml
  parameters:
    image_type: Windows2016-Azure
    image_readme_name: Windows2016-Readme.md