name: 'packer-build-action'
description: 'Build images with Packer'

inputs:
  image_type:
    description: >-
      One of the `ImageType` defined in `./helpers/GenerateResourcesAndImage.ps1`.
    required: true

runs:
  using: 'composite'
  steps:
    - name: Setup `packer`
      id: setup
      uses: hashicorp/setup-packer@main
      with:
        version: '1.10.1'

    - name: Pre-configure Packer
      id: preconfig
      shell: pwsh
      run: |
        switch -Wildcard ("${{ inputs.image_type }}") {
          "Ubuntu*" {
            $imageOs = "ubuntu"
          }
          "Windows*" {
            $imageOs = "windows"
          }
        }

        echo "::group::Pre-configure Packer"
        & {
          echo "image_os=${imageOs}";
        } | tee -a "$env:GITHUB_OUTPUT"
        echo "::endgroup::"

    - name: Build `${{ inputs.image_type }}`
      shell: pwsh
      env:
        PACKER_LOG: 1
      run: |
        Import-Module .\helpers\GenerateResourcesAndImage.ps1

        echo "::group::Generate Image"
        GenerateResourcesAndImage -ImageType ${{ inputs.image_type }}
        echo "::endgroup::"

        $readme = Join-Path "images" "${{ steps.preconfig.outputs.image_os }}" "${{ inputs.image_type }}-Readme.md"
        Get-Content -Path "$readme" | Out-File -Append -FilePath "$env:GITHUB_STEP_SUMMARY"

    - name: Upload generated reports
      uses: actions/upload-artifact@v4
      with:
        name: reports-${{ inputs.image_type }}
        path: |
          images/${{ steps.preconfig.outputs.image_os }}/${{ inputs.image_type }}-Readme.md
          images/${{ steps.preconfig.outputs.image_os }}/software-report.json
