name: Announcement
description: Submit an announcement
labels: [Announcement]
body:
  - type: textarea
    attributes:
      label: Breaking changes
      placeholder: Short description of the upcoming change
    validations:
      required: true
  - type: textarea
    attributes:
      label: Target date
      placeholder: Date of changes propagation start
    validations:
      required: true
  - type: textarea
    attributes:
      label: The motivation for the changes
      placeholder: Description of main reasons for this change
    validations:
      required: true
  - type: textarea
    attributes:
      label: Possible impact
      placeholder: Description of who might be impacted by this change
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Platforms affected
      options:
        - label: Azure DevOps
        - label: GitHub Actions
  - type: checkboxes
    attributes:
      label: Runner images affected
      options:
        - label: Ubuntu 20.04
        - label: Ubuntu 22.04
        - label: macOS 11
        - label: macOS 12
        - label: macOS 13
        - label: Windows Server 2019
        - label: Windows Server 2022
  - type: textarea
    attributes:
      label: Mitigation ways
      description: Steps or options for impact mitigation
    validations:
      required: true

