name: Tool request
description: Request a new tool or update to a tool
title: Update/Add [tool name]
labels: [feature request, needs triage]
body:
  - type: markdown
    attributes:
      value: "## Tool information"
  - type: input
    attributes:
      label: Tool name
    validations:
      required: true
  - type: input
    attributes:
      label: Tool license
      description: Type of licensing for desired tool.
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Add or update?
      options:
        - label: Add
        - label: Update
  - type: input
    attributes:
      label: Desired version
      description: Let us know if you're requesting a specific version, dev/RC, whatever is latest, etc.
    validations:
      required: true
  - type: input
    attributes:
      label: Approximate size
      description: Leave blank if unknown.
  - type: markdown
    attributes:
      value: "## If this is an add request"
  - type: textarea
    attributes:
      label: Brief description of tool
  - type: input
    attributes:
      label: URL for tool's homepage
  - type: textarea
    attributes:
      label: Provide a basic test case to validate the tool's functionality.
      description: This will be automatically formatted into code.
      render: bash
  - type: checkboxes
    attributes:
      label: Platforms where you need the tool
      options:
        - label: Azure DevOps
        - label: GitHub Actions
  - type: checkboxes
    attributes:
      label: Runner images where you need the tool
      options:
        - label: Ubuntu 20.04
        - label: Ubuntu 22.04
        - label: macOS 11
        - label: macOS 12
        - label: macOS 13
        - label: Windows Server 2019
        - label: Windows Server 2022
  - type: textarea
    attributes:
      label: Can this tool be installed during the build?
      description: If so, please provide a description with required steps. This will be automatically formatted into code.
      render: bash
  - type: input
    attributes:
      label: Tool installation time in runtime
      description: How long does it take to install the tool?
  - type: input
    attributes:
      label: Are you willing to submit a PR?
      description: We accept contributions!