#!/bin/bash
USERNAME="$1"
OLD_PASSWD="$2"
NEW_PASSWD="$3"

export PATH=/usr/bin:/usr/sbin:/usr/local/bin:/bin:/sbin

macosver="$(sw_vers | grep ProductVersion | awk {'print $2'})"

if [[ $macosver =~ 10.13.* ]]; then
    sudo /usr/bin/dscl . -passwd /Users/$USERNAME "$NEW_PASSWD"
else
    sudo /usr/sbin/sysadminctl -resetPasswordFor $USERNAME -newPassword "$NEW_PASSWD" -adminUser $USERNAME -adminPassword "$OLD_PASSWD"
fi

sudo /usr/bin/python /Users/$USERNAME/bootstrap/kcpassword.py "$NEW_PASSWD"
sudo /usr/bin/defaults write /Library/Preferences/com.apple.loginwindow autoLoginUser "$USERNAME"
/usr/bin/security set-keychain-password -o "$OLD_PASSWD" -p "$NEW_PASSWD" /Users/$USERNAME/Library/Keychains/login.keychain