schedules:
- cron: "0 0 * * 0"
  displayName: Weekly
  branches:
    include:
    - main
  always: true

trigger:
  batch: true
  
pr:
  autoCancel: true
  branches:
    include:
    - main
  paths:
    exclude:
    - images/win

jobs:
- template: image-generation.yml
  parameters:
    image_type: ubuntu2004
    image_readme_name: Ubuntu2004-README.md