trigger: none
# batch: true

pr:
  autoCancel: true
  branches:
    include:
    - main
  paths:
    exclude:
    - images/linux

jobs:
- template: image-generation.yml
  parameters:
    image_type: windows2019
    image_readme_name: Windows2019-Readme.md
