schedules:
- cron: "0 0 * * *"
  displayName: Daily
  branches:
    include:
    - main
  always: true

trigger: none
pr:
  autoCancel: false
  branches:
    include:
    - main

jobs:
- template: image-generation.yml
  parameters:
    image_type: windows
    image_readme_name: Windows-Readme.md
