
trigger: none

pr:
  autoCancel: true
  branches:
    include:
    - main
pool:
 name: ci-agent-pool
 vmImage: Ent-Packer
 
jobs:
- template: image-generation.yml
  parameters:
    image_type: windows2022
    image_readme_name: Windows2022-Readme.md
    image_template_name: windows-2022.pkr.hcl
