#!/bin/bash
################################################################################
##  File:  preparemetadata.sh
##  Desc:  This script adds a image title information to the metadata
##         document
################################################################################

source $HELPER_SCRIPTS/document.sh

WriteItem "<!--- DO NOT EDIT - This markdown file is autogenerated. -->"

if [ $ANNOUNCEMENTS ]; then
    Announcements="| Announcements |\n|-|\n"
    IFS=';;' read -ra rawAnnouncements <<< "$UBUNTU_ANNOUNCEMENTS"
    for rawAnnouncement in "${rawAnnouncements[@]}"; do
        if [ $rawAnnouncement ]; then
            IFS="===" read -ra announcement <<< "$rawAnnouncement"
            Announcements+="| [${announcement[0]}](${announcement[3]}) |\n"
        fi
    done
    WriteItem $Announcements
fi


AddTitle "$(lsb_release -ds)"
WriteItem "The following software is installed on machines with the $IMAGE_VERSION update."
WriteItem "***"
