name: Ubuntu - Build template for Ubuntu 26.04

on:
  workflow_dispatch:
    inputs:
      servertype:
        type: choice
        required: true
        options:
          - standard
          - large
          - xlarge
        default: "standard"

env:
  os: "ubuntu26"
  packer_template: "build.ubuntu-26_04.pkr.hcl"

jobs:
  Set-Variables:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Assign ENV variables to workflow outputs
        id: env
        run: |
          echo "os=${{ env.os }}" >> $GITHUB_OUTPUT
          echo "packer_template=${{ env.packer_template }}" >> $GITHUB_OUTPUT

      - name: Display Variable server os
        run: echo "${{ steps.env.outputs.os }}"

      - name: Display Variable packer template
        run: echo "${{ steps.env.outputs.packer_template }}"

      - name: Display Variable server type
        run: echo "${{ inputs.servertype }}"

    outputs:
      os: ${{ steps.env.outputs.os }}
      packer_template: ${{ steps.env.outputs.packer_template }}

  Trigger-CollectInformations:
    needs: Set-Variables

    permissions:
      contents: read
      pull-requests: read

    uses: ./.github/workflows/ubuntu_trigger-collect-informations.yml
    with:
      os: ${{ needs.Set-Variables.outputs.os }}

  Trigger-ImageBuilder:
    needs:
      - Set-Variables
      - Trigger-CollectInformations

    permissions:
      contents: write
      pull-requests: write

    uses: ./.github/workflows/ubuntu_trigger-build-new-templates.yml
    with:
      release_name: ${{ needs.Trigger-CollectInformations.outputs.ReleaseName }}
      release_tag: ${{ needs.Trigger-CollectInformations.outputs.ReleaseTag }}
      hcl_filename: ${{ needs.Set-Variables.outputs.packer_template }}
      release_no: ${{ needs.Trigger-CollectInformations.outputs.ReleaseNo }}
      readme_file: ${{ needs.Trigger-CollectInformations.outputs.ReadmeFile }}
      gh_pr_labels: ${{ needs.Trigger-CollectInformations.outputs.GitHubPrLabels }}

    secrets: inherit

  Trigger-CleanupOnFailure:
    if: ${{ failure() || cancelled() }}

    needs:
      - Set-Variables
      - Trigger-CollectInformations
      - Trigger-ImageBuilder

    permissions:
      contents: write

    uses: ./.github/workflows/ubuntu_trigger-cleanup-on-failure.yml
    with:
      ReleaseTag: ${{ needs.Trigger-CollectInformations.outputs.ReleaseTag }}
      HCloudObjectName: ${{ needs.Trigger-CollectInformations.outputs.HCloudObjectName }}

    secrets: inherit
