name: Build runner image

on:
  workflow_call:
    secrets:
      ACTIONS_RUNNER_BUILDER_AZURE_SERVICE_PRINCIPAL:
        required: true

jobs:
  build-runner-image:
    name: Build runner image
    runs-on: "[\"windows-latest\"]"
    defaults:
      run:
        shell: pwsh
    strategy:
      matrix:
        machine-type: "[\"windows-latest\"]"
        timeout-minutes:
        - 360
    timeout-minutes: 360
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: "recursive"
