name: Build Image
on: [push, pull_request]

jobs:
  build:
    name: "BuildImage"
    runs-on: self-hosted
    steps:

      - name: Hello world
        run: echo check work machine

      - name: Exit
        run: exit 1