# CI Validation

name: Linter

on:
  pull_request:
    branches: [ main ]
    paths:
      - '**.json'
      - '**.md'
      - '**.sh'

jobs:
  build:
    name: Lint JSON & MD files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter/slim@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_JSON: true
          VALIDATE_MARKDOWN: true
          DEFAULT_BRANCH: ${{ github.base_ref }}
          FILTER_REGEX_EXCLUDE: .*images/*/.*-Readme.md

      - name: Checking shebang lines in MacOS and Ubuntu releases.
        run: ./images.CI/shebang-linter.ps1
        shell: pwsh

# This workflow is used to lint JSON, Markdown, and Shell script files in the repository.
# It uses the github/super-linter action to perform the linting.
# Learn more about the super-linter at https://github.com/github/super-linter

# To customize this workflow for different file types, you can modify the `paths` section above.
# For example, to add support for YAML files, you can add '**.yml' to the paths section.
