run-name: macOS-12_unstable.${{ github.run_id }}.${{ github.run_attempt }}
on:
  workflow_dispatch:
    inputs:
      CUSTOM_REPOSITORY:
        description: 'Custom repository (owner/repo)'
        required: false
      CUSTOM_REPOSITORY_COMMIT_HASH:
        description: 'Commit hash'
        required: false

jobs:
  macOS_12:
    if: (github.event_name == 'workflow_dispatch') || (github.event_name == 'schedule')
    name: macOS-12_unstable.${{ github.run_id }}.${{ github.run_attempt }}
    uses: ./.github/workflows/macos-generation.yml
    with:
      image_label: 'macOS Monterey'
      base_image_name: 'clean-macOS-12-380Gb-runner'
      template_path: 'templates/macOS-12.json'
      target_datastore: 'ds-image'
      custom_repo: ${{ github.event.inputs.CUSTOM_REPOSITORY }}
      custom_repo_commit_hash: ${{ github.event.inputs.CUSTOM_REPOSITORY_COMMIT_HASH }}
    secrets: inherit
