name: test-ubuntu-ruby

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-20.04', 'ubuntu-22.04']
        ruby: ['3.1', '3.2.4', '3.2', '3.3']
        bundler: ['2.5.0', '2.5.10', '2.5.11', '2.5.12','2.5.13','2.5.14','2.5.15', '2.5.16', '2.5.17']

    steps:
      - uses: actions/checkout@v4
        
      # - name: permissions check-1
      #   run: |
      #     ls -la /opt/hostedtoolcache/Ruby/3.1.*/x64/lib/ruby/gems/3.1.0/gems
      #     ls -la /opt/hostedtoolcache/Ruby/3.2.*/x64/lib/ruby/gems/3.2.0/gems
      #   shell: bash
      #   if: always()

      - name: Install Ruby version ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler: ${{ matrix.bundler }}
        env:
          BUNDLE_GEMFILE: Gemfile
        if: always()

      # - run: chmod -R o-w /opt/hostedtoolcache/Ruby/3.2.5/x64/lib/ruby/gems/3.2.0/gems
      #   if: always()

      # - name: permissions check-2
      #   run: |
      #     ls -la /opt/hostedtoolcache/Ruby/3.1.*/x64/lib/ruby/gems/3.1.0/gems
      #     ls -la /opt/hostedtoolcache/Ruby/3.2.*/x64/lib/ruby/gems/3.2.0/gems
      #     ls -la /opt/hostedtoolcache/Ruby/3.3.*/x64/lib/ruby/gems/3.3.0/gems
      #   shell: bash
      #   if: always()

      # - name: Prepare Gemfile
      #   if: always()
      #   run: |
      #     cat <<EOF > Gemfile
      #     source 'https://rubygems.org'

      #     gem 'faraday'
      #     EOF
      
      - name: bundle install
        if: always()
        run: |
          bundler --version
          bundle install
