name: Test
on:
  pull_request:
    types: [labeled]

jobs:
  build:
    name: test
    runs-on: self-hosted
    if: github.event.label.name == 'bug'

    steps:
    - name: Test
      run: $env:Path.Split(";")
      
    - name: Test2
      run: az --version
