name: Trigger Ubuntu24.04 CI
run-name: Ubuntu24.04 - ${{ github.event.pull_request.title }}

on:
  pull_request_target:
    types: labeled
    paths:
    - 'images/ubuntu/**'

defaults:
  run:
    shell: pwsh

jobs:
  Ubuntu_2404:
    if: github.event.label.name == 'CI ubuntu-all' || github.event.label.name == 'CI ubuntu-2404'
    uses: ./.github/workflows/trigger-ubuntu-win-build.yml
    with:
      image_type: 'ubuntu2404'
    secrets: inherit
