name: Ubuntu 24.04 by Terraform
run-name: Ubuntu24.04

on:
  push:
      paths:
      - 'images/ubuntu/**'
      branches:
      - main     
  workflow_dispatch: 
    inputs:
      run_packer:
        type: boolean
        description: Run Packer to build image
        default: false

jobs:
  Ubuntu_2404:
    uses: ./.github/workflows/terraform-execution.yml
    with:
      image_type: 'ubuntu'
      image_type_version: '24.04'
      image_readme_path: 'ubuntu/Ubuntu2404-Readme.md'
      short_image_name: 'u'
      state: tf-ubuntu-2404.tfstate
      run_packer: ${{ github.event.inputs.run_packer }}
    secrets: inherit
