on:
  push:
    branches: [ mlobanov/ubuntu-software-report ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - run: |
          Get-ChildItem env:
        shell: pwsh

      - run: |
          mkdir -p /tmp/report
          
      - run: |
          mkdir -p  images/linux/scripts/SoftwareReport/software-report-base
          cp helpers/software-report-base/* images/linux/scripts/SoftwareReport/software-report-base
          ls -la images/linux/scripts/SoftwareReport/software-report-base

      - run: |
          images/linux/scripts/SoftwareReport/SoftwareReport.Generator.ps1 -OutputDirectory "/tmp/report"
        shell: pwsh
          
      - run: |
            cat /tmp/report/systeminfo.md
      - run: |
            cat /tmp/report/systeminfo.json
