name: Ubuntu 22.04 by Terraform
run-name: Ubuntu22.04

on:
  push:
      paths:
      - 'images/ubuntu/**'
      branches:
      - main     
  workflow_dispatch: 
    inputs:
      run_packer:
        type: boolean
        description: Run Packer to build image
        default: false

jobs:
  Ubuntu_2204:
    uses: ./.github/workflows/terraform-execution.yml
    with:
      image_type: 'ubuntu'
      image_type_version: '22.04'
      image_readme_path: 'ubuntu/Ubuntu2204-Readme.md'
      short_image_name: 'u'
      state: tf-ubuntu-2204.tfstate
      run_packer: '${{ github.event.inputs.run_packer }}'
    secrets: inherit
