name: Trigger Ubuntu24.04 CI using Terraform
run-name: Ubuntu24.04 - ${{ github.event.pull_request.title }}

on:
  push:
      paths:
      - 'images/ubuntu/**'
      branches:
        - main     
  workflow_dispatch: 

jobs:
  Ubuntu_2404:
    uses: ./.github/workflows/terraform-execution.yml
    with:
      image_type: 'ubuntu'
      image_type_version: '24.04'
    secrets: inherit
