name: Ubuntu - Trigger build new templates

on:
  workflow_call:
    inputs:
      release_name:
        required: true
        type: string
      release_tag:
        required: true
        type: string
      hcl_filename:
        required: true
        type: string
      release_no:
        required: true
        type: string
      hcloud_server_location:
        required: true
        type: string
      hcloud_server_image:
        required: true
        type: string
      hcloud_server_type:
        required: true
        type: string
      hcloud_name:
        required: true
        type: string
      readme_file:
        required: true
        type: string       
      gh_pr_labels:
        required: true
        type: string


jobs:
  Create-NewBranch:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: read

    steps:
      - name: Generate app token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        id: generate-token
        with:
          client-id: ${{ secrets.GH_APP_RIHC_ID }}
          private-key: ${{ secrets.GH_APP_RIHC_PRIVATE_KEY }}
    
      - name: Create a new branch
        uses: peterjgrainger/action-create-branch@4b81ce657e255acd677cc6c55c9c763654be3aef # v4.0.0
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
        with:
          branch: releases/${{ inputs.release_tag }}

          
  Create-ServerTemplate:
    needs: Create-NewBranch
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: read

    steps:       
      - name: Generate app token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        id: generate-token
        with:
          client-id: ${{ secrets.GH_APP_RIHC_ID }}
          private-key: ${{ secrets.GH_APP_RIHC_PRIVATE_KEY }}
          
      - name: Checkout new created branch
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: releases/${{ inputs.release_tag }}


      - name: Setup `packer`
        uses: hashicorp/setup-packer@c3d53c525d422944e50ee27b840746d6522b08de # v3.2.0
        id: setup
        with:
          version: latest

      - name: Run `packer init`
        id: init
        run: packer init ./images/ubuntu/templates/
        env:
          PACKER_GITHUB_API_TOKEN: ${{ steps.generate-token.outputs.token }}

      - name: Run `packer validate`
        id: validate
        run: packer validate -only "${{ inputs.hcloud_server_image }}*" ./images/ubuntu/templates/
        env:
          HCLOUD_TOKEN: ${{ secrets.HCLOUD_TOKEN }}
          HCLOUD_OBJECT_NAME: ${{ inputs.hcloud_name }}
          HCLOUD_SERVER_LOCATION: ${{ inputs.hcloud_server_location }}
          HCLOUD_SERVER_IMAGE: ${{ inputs.hcloud_server_image }}
          HCLOUD_SERVER_TYPE: ${{ inputs.hcloud_server_type }}
          IMAGE_VERSION: ${{ inputs.release_no }}
          PACKER_GITHUB_API_TOKEN: ${{ steps.generate-token.outputs.token }}

      - name: Run `packer build`
        id: build
        run: packer build -only "${{ inputs.hcloud_server_image }}*" ./images/ubuntu/templates/
        env:
          HCLOUD_TOKEN: ${{ secrets.HCLOUD_TOKEN }}
          HCLOUD_OBJECT_NAME: ${{ inputs.hcloud_name }}
          HCLOUD_SERVER_LOCATION: ${{ inputs.hcloud_server_location }}
          HCLOUD_SERVER_IMAGE: ${{ inputs.hcloud_server_image }}
          HCLOUD_SERVER_TYPE: ${{ inputs.hcloud_server_type }}
          IMAGE_VERSION: ${{ inputs.release_no }}
          PACKER_LOG: ${{ vars.PACKER_LOG }}
          PACKER_GITHUB_API_TOKEN: ${{ steps.generate-token.outputs.token }}
          
          
      - name: Upload file software-report.json to artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a  # v7.0.1
        with:
          name: software-report.json
          path: images/ubuntu/software-report.json
          if-no-files-found: error
          overwrite: true
          retention-days: 1

      - name: Upload file sbom.json.zip to artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a  # v7.0.1
        with:
          name: sbom.json.zip
          path: images/ubuntu/sbom.json.zip
          if-no-files-found: error
          overwrite: true
          retention-days: 1

      - name: Remove sbom.json.zip and software-report.json
        #uses: JesseTG/rm@a7df6e6edbbd7ea7440ea0a57342fc7798950e4f # v1.0.3
        #with:
        #  path: images/ubuntu/software-report.json
        run: |
          rm images/ubuntu/software-report.json
          rm images/ubuntu/sbom.json.zip
      
      - name: Commit & Push changes
        uses: actions-js/push@5a7cbd780d82c0c937b5977586e641b2fd94acc5 # v1.5
        with:
          branch: releases/${{ inputs.release_tag }}
          github_token: ${{ steps.generate-token.outputs.token }}
          force: true


  Create-PullRequest:
    needs:
      - Create-ServerTemplate
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write
      
    steps:
      - name: Generate app token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        id: generate-token
        with:
          client-id: ${{ secrets.GH_APP_RIHC_ID }}
          private-key: ${{ secrets.GH_APP_RIHC_PRIVATE_KEY }}
          
      - name: Checkout new created branch
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: '0'
          ref: releases/${{ inputs.release_tag }}

      - name: Save file ${{ inputs.readme_file }} in variable
        id: readme
        uses: jaywcjlove/github-action-read-file@935d2b17432f2350fd155a3ccbd3f2934be9e410 # v2.1.0
        with:
          branch: releases/${{ inputs.release_tag }}
          path: images/ubuntu/${{ inputs.readme_file }}
          
      - name: Create pull request
        id: pullrequest
        uses: devops-infra/action-pull-request@b2895bff2ff66579f6704d717a1ea75fad919e84 # v1.0.2
        with:
          github_token: ${{ steps.generate-token.outputs.token }}
          source_branch: releases/${{ inputs.release_tag }}
          target_branch: customize
          title: ${{ inputs.release_name }}
          body: ${{ steps.readme.outputs.content }}
          label: ${{ inputs.gh_pr_labels }}
          assignee: dwydler


      - name: Merge the pull request
        uses: pascalgn/automerge-action@7961b8b5eec56cc088c140b56d864285eabd3f67 # v0.16.4
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
          PULL_REQUEST: ${{ steps.pullrequest.outputs.pr_number }}
          MERGE_LABELS: ${{ inputs.release_tag }}
          UPDATE_LABELS: ${{ inputs.release_tag }}
          MERGE_COMMIT_MESSAGE: "${{ inputs.release_name }} (#${{ steps.pullrequest.outputs.pr_number }})"
          MERGE_METHOD: "squash"
          MERGE_RETRIES: 10
          MERGE_RETRY_SLEEP: 30000 # milliseconds
          MERGE_READY_STATE: clean

      - name: Download file software-report.json from artifact
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c  # v8.0.1
        with:
          name: software-report.json

      - name: Download file sbom.json.zip from artifact
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c  # v8.0.1
        with:
          name: sbom.json.zip          

      - name: Create a new release
        uses: ncipollo/release-action@339a81892b84b4eeb0f6e744e4574d79d0d9b8dd # v1.21.0
        with:
          tag: ${{ inputs.release_tag }}
          name: ${{ inputs.release_name }}
          body: ${{ steps.readme.outputs.content }}
          token: ${{ steps.generate-token.outputs.token }}
          artifacts: software-report.json,sbom.json.zip
        
      - name: Delete all artifacts associated with the run 
        uses: geekyeggo/delete-artifact@176a747ab7e287e3ff4787bf8a148716375ca118  # v6.0.0
        with:
          name: |
            software-report.json
            sbom.json.zip
