name: Ubuntu1804
on:
  pull_request:
    paths: "images/linux/**"
    types: [labeled]

jobs:
  build:
    name: ubuntu1804 job
    runs-on: ubuntu-latest
    if: github.event.label.name == 'test-ubuntu1804'

    steps:
      - name: Build ubuntu1804
        run: |
          echo "Long build for ubuntu1804"