name: Ubuntu20.04 by Terraform
run-name: Ubuntu20.04

on:
  push:
      paths:
      - 'images/ubuntu/**'
      branches:
      - main     
  workflow_dispatch: 

jobs:
  Ubuntu_2404:
    uses: ./.github/workflows/terraform-execution.yml
    with:
      image_type: 'ubuntu'
      image_type_version: '20.04'
      image_readme_path: 'ubuntu/Ubuntu2004-Readme.md'
      short_image_name: 'u'
    secrets: inherit
