name: Ubuntu1604
on:
  pull_request:
    paths: "images/win/**"
    types: [labeled]

jobs:
  build:
    name: ubuntu1804 job
    runs-on: ubuntu-latest
    if: github.event.label.name == 'test-ubuntu1604'

    steps:
      - name: Build ubuntu1604
        run: |
          echo "Long build for ubuntu1604"