name: Ubuntu 20.04 by Terraform
run-name: Ubuntu20.04

on:
  push:
      paths:
      - 'images/ubuntu/**'
      branches:
      - main     
  workflow_dispatch: 
    inputs:
      run_packer:
        type: boolean
        description: Run Packer to build image
        default: true
    
jobs:
  Ubuntu_2004:
    uses: ./.github/workflows/terraform-execution.yml
    with:
      image_type: 'ubuntu'
      image_type_version: '20.04'
      image_readme_path: 'ubuntu/Ubuntu2004-Readme.md'
      short_image_name: 'u'
      state: tf-ubuntu-2004.tfstate
      run_packer: '${{ inputs.run_packer }}'
    secrets: inherit
