name: Trigger Ubuntu20.04 CI
run-name: Ubuntu20.04 - ${{ github.event.pull_request.title }}

on:
  pull_request:
    paths:
    - 'images/ubuntu/**'

defaults:
  run:
    shell: pwsh

jobs:
  Ubuntu_2004:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'CI ubuntu-all') || contains(github.event.pull_request.labels.*.name, 'CI ubuntu-2004')
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: ./.github/actions/packer-build-action
        id: build
        with:
          image_type: Ubuntu2004
