# Sync this with the MS upstream repo that is was forked from

name: Sync Fork

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  updateMainFromFork:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
          token: ${{ secrets.FORK_SYNC_PAT }}
      
      - name: Do this manually
        run: |
         git remote add upstream https://github.com/actions/virtual-environments.git
         git config --global user.email "toddwalstad@eaton.com"
         git config --global user.name "toddwalstad-eaton"
         git fetch upstream
         git merge upstream/main --allow-unrelated-histories -s recursive -Xtheirs
         git checkout --theirs .
         git add .
         git push --force  origin main 
