name: Validate JSON Schema

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate-json-schema:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install GripDevJsonSchemaValidator module
        shell: pwsh
        run: Install-Module -Name GripDevJsonSchemaValidator -Force -Scope CurrentUser

      - name: Validate JSON Schema
        shell: pwsh
        run: ./helpers/CheckJsonSchema.ps1
