name: Windows 2022 by Terraform
run-name: Windows2022

on:
  push:
      paths:
      - 'images/windows/**'
      branches:
      - main     
  workflow_dispatch: 
    inputs:
      run_packer:
        type: boolean
        description: Run Packer to build image
        default: false

jobs:
  win2022:
    uses: ./.github/workflows/terraform-execution.yml
    with:
      image_type: 'windows'
      image_type_version: '2022'
      image_readme_path: 'windows/Windows2022-Readme.md'
      short_image_name: 'w'
      state: tf-windows-2022.tfstate
      run_packer: ${{ github.event_name == 'run_packer' || fromJSON(inputs.build) }}
    secrets: inherit
