name: Windows 2019 by Terraform
run-name: Windows2019

on:
  push:
      paths:
      - 'images/windows/**'
      branches:
      - main     
  workflow_dispatch: 

jobs:
  CommunityGallery:
    uses: ./.github/workflows/terraform-execution.yml
    with:
      image_type: 'windows'
      image_type_version: '2019'
      image_readme_path: 'windows/Windows2019-Readme.md'
      short_image_name: 'w'
      state: tf-community-gallery-base.tfstate
      directory: './terraform_base'
    secrets: inherit  
  win2019:
    uses: ./.github/workflows/terraform-execution.yml
    needs: CommunityGallery
    with:
      image_type: 'windows'
      image_type_version: '2019'
      image_readme_path: 'windows/Windows2019-Readme.md'
      short_image_name: 'w'
      state: tf-windows-2019.tfstate
    secrets: inherit
