name: Trigger Windows11 Arm64 CI
run-name: Windows11 Arm64 - ${{ github.event.pull_request.title }}

on:
  pull_request_target:
    types: labeled
    paths:
    - 'images/windows/**'

defaults:
  run:
    shell: pwsh

jobs:
  Windows_11_Arm64:
    if: github.event.label.name == 'CI windows-all' || github.event.label.name == 'CI windows-11-arm64'
    uses: ./.github/workflows/trigger-ubuntu-win-build.yml
    with:
      image_type: 'windows11-arm64'
    secrets: inherit
